[2023-09-10T21:39:43.124+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process-employees.create_employees_temp_table scheduled__2023-08-14T00:00:00+00:00 [queued]>
[2023-09-10T21:39:43.138+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process-employees.create_employees_temp_table scheduled__2023-08-14T00:00:00+00:00 [queued]>
[2023-09-10T21:39:43.139+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-09-10T21:39:43.153+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_employees_temp_table> on 2023-08-14 00:00:00+00:00
[2023-09-10T21:39:43.165+0000] {standard_task_runner.py:57} INFO - Started process 62 to run task
[2023-09-10T21:39:43.173+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'process-employees', 'create_employees_temp_table', 'scheduled__2023-08-14T00:00:00+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/process-employees.py', '--cfg-path', '/tmp/tmpazrims5u']
[2023-09-10T21:39:43.180+0000] {standard_task_runner.py:85} INFO - Job 55: Subtask create_employees_temp_table
[2023-09-10T21:39:43.258+0000] {task_command.py:410} INFO - Running <TaskInstance: process-employees.create_employees_temp_table scheduled__2023-08-14T00:00:00+00:00 [running]> on host d56c691d705a
[2023-09-10T21:39:43.392+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process-employees' AIRFLOW_CTX_TASK_ID='create_employees_temp_table' AIRFLOW_CTX_EXECUTION_DATE='2023-08-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-14T00:00:00+00:00'
[2023-09-10T21:39:43.396+0000] {sql.py:265} INFO - Executing: 
            DROP TABLE IF EXISTS employees_temp;
            CREATE TABLE employees_temp (
                "Serial Number" NUMERIC PRIMARY KEY,
                "Company Name" TEXT,
                "Employee Markme" TEXT,
                "Description" TEXT,
                "Leave" INTEGER
            );
[2023-09-10T21:39:43.439+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 266, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 181, in get_db_hook
    return self._hook
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 143, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 434, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `tutorial_pg_conn` isn't defined
[2023-09-10T21:39:43.447+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=process-employees, task_id=create_employees_temp_table, execution_date=20230814T000000, start_date=20230910T213943, end_date=20230910T213943
[2023-09-10T21:39:43.463+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 55 for task create_employees_temp_table (The conn_id `tutorial_pg_conn` isn't defined; 62)
[2023-09-10T21:39:43.508+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-09-10T21:39:43.532+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
